language: node_js
node_js:
- 10.16.0
script:
- npm run build
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 121.37.132.134 
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
after_success:
- rsync -az --delete ./dist/* ubuntu@121.37.132.134:/home/ubuntu/fabric-client-demo-build/
